const tokenIssuer = require('jsonwebtoken');
const cipherService = require('bcryptjs');
const SystemAccount = require('../models/User');

const ENV_SECRET = process.env.JWT_SECRET || 'super-secret-key-for-dev';

/**
 * Handle initial registration of operators into the system.
 */
const enrolOperator = async (req, res) => {
    try {
        const { username, email, password, role } = req.body;

        // Gatekeeper check: Only admins can elevate another admin or create the first one
        if (role === 'Admin') {
            const activeAdminRecords = await SystemAccount.findOne({ where: { assignedRole: 'Admin' } });

            // If an admin already exists in the local database, the requester MUST be an authenticated Admin
            if (activeAdminRecords && (!req.user || req.user.assignedRole !== 'Admin')) {
                return res.status(403).json({
                    error: 'Insufficient privilege ceiling. Administrators must be generated by existing peers.'
                });
            }
        }

        // Secure the secret payload
        const encryptionSalt = await cipherService.genSalt(10);
        const guardedSecret = await cipherService.hash(password, encryptionSalt);

        const newOperator = await SystemAccount.create({
            operatorName: username,
            contactEmail: email,
            secureSecret: guardedSecret,
            assignedRole: role || 'Viewer',
        });

        // Issue Identity Token
        const identityToken = tokenIssuer.sign(
            { sub: newOperator.accountId, priv: newOperator.assignedRole },
            ENV_SECRET,
            { expiresIn: '24h' }
        );

        res.status(201).json({
            message: 'Operator successfully enrolled inside the system bounds.',
            operatorProfile: {
                id: newOperator.accountId,
                alias: newOperator.operatorName,
                contact: newOperator.contactEmail,
                clearance: newOperator.assignedRole,
            },
            token: identityToken,
        });
    } catch (error) {
        if (error.name === 'SequelizeUniqueConstraintError') {
            return res.status(400).json({ error: 'Conflict: This alias or contact email is already bound to an active operator.' });
        }
        res.status(500).json({ error: 'Critical system error during operator enrollment phase.' });
    }
};

/**
 * Handle authentication and token provisioning for existing operators.
 */
const initiateSession = async (req, res) => {
    try {
        const { email, password } = req.body;

        const operatorMatch = await SystemAccount.findOne({ where: { contactEmail: email } });
        if (!operatorMatch) {
            return res.status(401).json({ error: 'Authentication challenge failed. Invalid profile trace.' });
        }

        if (operatorMatch.accountState !== 'Active') {
            return res.status(403).json({ error: 'Authentication rejected. Profile is suspended.' });
        }

        const secretMatches = await cipherService.compare(password, operatorMatch.secureSecret);
        if (!secretMatches) {
            return res.status(401).json({ error: 'Authentication challenge failed. Secret payload mismatch.' });
        }

        const sessionKey = tokenIssuer.sign(
            { sub: operatorMatch.accountId, priv: operatorMatch.assignedRole },
            ENV_SECRET,
            { expiresIn: '24h' }
        );

        res.json({
            message: 'Session successfully synchronized.',
            operatorProfile: {
                id: operatorMatch.accountId,
                alias: operatorMatch.operatorName,
                contact: operatorMatch.contactEmail,
                clearance: operatorMatch.assignedRole,
            },
            token: sessionKey,
        });
    } catch (error) {
        res.status(500).json({ error: 'Critical system error during session hand-shake.' });
    }
};

module.exports = {
    enrolOperator,
    initiateSession,
};
